# Generated by Django 5.2 on 2025-05-05 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_trainingplan_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='trainercourse',
            options={'verbose_name': 'Назначение курса', 'verbose_name_plural': 'Назначения курсов'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='trainers',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='active',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='trainercourse',
            unique_together={('trainer', 'course')},
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='client_request',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Название курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='valid_until',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Действует до'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainercourse',
            name='assigned_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата назначения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='request',
            field=models.OneToOneField( default=1, on_delete=django.db.models.deletion.CASCADE, to='core.clientrequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveSmallIntegerField(help_text='От\xa01 до\xa0100', verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='trainercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='trainercourse',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_courses', to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
        migrations.RemoveField(
            model_name='trainercourse',
            name='enrolled_at',
        ),
    ]
